### ISSUE TITLE
Unable to use sliding sync proxy in chat.hashi.sbs

### ISSUE THREAD

**Issue by 0x7c26** [Whimsies-YAT/Issue_Tracker#1]
I enabled the sliding synchronization proxy in the laboratory settings of chat.hashi.sbs, but when I filled in the sliding synchronization proxy address of hashi.sbs, it prompted "proxy health check: client using https://hashi.sbs but server is as https://chatserver.hashi.sbs"

Environment
 - Device: computer
 - OS: linux
 - Browser: edge

**Comment by MomentQYC** [comment]
Fixed
