### ISSUE TITLE
[Deactivate Account] Can't deactivate account when use google account sign up

### ISSUE THREAD

**Issue by mrljdx** [Whimsies-YAT/Issue_Tracker#2]
**Describe the bug**
After I logged in using my Google account, I went to the settings page to delete my current account, only to find out that I needed to enter an account password. However, since I logged in using my Google account and did not set a password, this seems to be a bug. The same issue in Element is directly verified with the Google account for deletion.

**To Reproduce**
1. Log in using a Google account.
2. Go to the account settings interface and select delete account.

**Expected behavior**
Aways，This bug is consistently reproducible.

**Screenshots**
![image](https://github.com/Whimsies-YAT/Issue_Tracker/assets/4383863/84148f7c-b571-4d04-8893-86c48c3a3736)

**Comment by MomentQYC** [comment]
> **Describe the bug** After I logged in using my Google account, I went to the settings page to delete my current account, only to find out that I needed to enter an account password. However, since I logged in using my Google account and did not set a password, this seems to be a bug. The same issue in Element is directly verified with the Google account for deletion.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Log in using a Google account.
> 2. Go to the account settings interface and select delete account.
> 
> **Expected behavior** Aways，This bug is consistently reproducible.
> 
> **Screenshots** ![image](https://private-user-images.githubusercontent.com/4383863/285628695-84148f7c-b571-4d04-8893-86c48c3a3736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NDUzNDgsIm5iZiI6MTcwNjg0NTA0OCwicGF0aCI6Ii80MzgzODYzLzI4NTYyODY5NS04NDE0OGY3Yy1iNTcxLTRkMDQtODg5My04NmM0OGMzYTM3MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMDMzNzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2QwYmExN2QxOTg4Mjg3MzZjZThkOTZmYjA4NTZjM2VjOTM3NzM1N2IwNzg4ZTExMDFmMmQzMzg5NTJhNjJkZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pCuXycGg2L78xDxpP6RjI1ADojKdP8hUXUVPsiCUEX8)

We apologize that we were previously working on other issues and did not notice the report.
If you are still having problems, please reply to us or contact our support email.
